"""Report-domain tables: reports, idempotency keys.

IdempotencyKey lives here because it scopes the /v1/reports POST contract
(§4 API contract). RateLimitHit lives in auth.models for the same reason
inverted (magic-link issuance is its dominant use).

The search_vector column is a Postgres GENERATED ALWAYS AS (...) STORED
tsvector — it's modeled as Computed below for SQLAlchemy ORM visibility,
but the baseline Alembic migration writes the raw CREATE TABLE SQL
because Alembic autogenerate can't round-trip GENERATED columns.
"""

from datetime import datetime, timedelta
from typing import Any
from uuid import UUID

from sqlalchemy import (
    BigInteger,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, TSVECTOR
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.sql import func

from app.db.base import Base
from app.db.mixins import ExpiringMixin


class Report(Base):
    __tablename__ = "reports"

    # UUID v7 generated by app (uuid_utils.uuid7()) — pass into the model;
    # no server_default because we want time-sortable IDs not gen_random_uuid().
    id: Mapped[UUID] = mapped_column(PGUUID(as_uuid=True), primary_key=True)
    customer_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(
        String, nullable=False, server_default=""
    )
    tags: Mapped[list[str]] = mapped_column(
        ARRAY(Text), nullable=False, server_default="{}"
    )
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    s3_key: Mapped[str] = mapped_column(String, nullable=False)
    supplementary_files: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, server_default="[]"
    )
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    # Tsvector mirrors the GENERATED column declared in raw SQL in the baseline
    # migration. ORM treats it as read-only via Computed(persisted=True).
    # GENERATED column populated by reports_tsv() — IMMUTABLE wrapper created in
    # the baseline migration. See migration for rationale (Postgres rejects raw
    # to_tsvector in GENERATED because it's STABLE not IMMUTABLE).
    search_vector: Mapped[Any] = mapped_column(
        TSVECTOR,
        Computed("reports_tsv(title, description, tags)", persisted=True),
    )

    __table_args__ = (
        Index(
            "reports_pagination_idx",
            "customer_id",
            "generated_at",
            "id",
            postgresql_using="btree",
        ),
        Index("reports_search_idx", "search_vector", postgresql_using="gin"),
        Index("reports_tags_idx", "tags", postgresql_using="gin"),
    )


class IdempotencyKey(Base, ExpiringMixin):
    __tablename__ = "idempotency_keys"
    __ttl__ = timedelta(hours=24)

    customer_id: Mapped[UUID] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("customers.id", ondelete="CASCADE"),
        primary_key=True,
    )
    key: Mapped[str] = mapped_column(String, primary_key=True)
    response_body: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    status_code: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (Index("idempotency_keys_expires_idx", "expires_at"),)
