"""baseline — all M1 tables per PLAN.md §3.1

Revision ID: 20260511_0830
Revises:
Create Date: 2026-05-11

Hand-written, not autogenerated. Postgres-specific:
- reports.search_vector is a GENERATED ALWAYS AS (...) STORED tsvector
- reports_pagination_idx orders DESC on (generated_at, id)
- GIN indexes on search_vector and tags
- gen_random_uuid() requires Postgres 13+ (built-in, no extension needed)
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "20260511_0830"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE customers (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            name            TEXT NOT NULL,
            allowlist_emails TEXT[] NOT NULL DEFAULT '{}',
            api_key_hash    TEXT NOT NULL,
            api_key_prefix  TEXT NOT NULL,
            is_active       BOOLEAN NOT NULL DEFAULT true,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute(
        "CREATE INDEX customers_api_key_prefix_idx ON customers (api_key_prefix);"
    )

    # Postgres requires GENERATED columns to use IMMUTABLE expressions, but
    # to_tsvector(regconfig, text) is STABLE (the regconfig lookup goes through
    # the system catalog). Standard workaround: wrap the expression in an
    # IMMUTABLE SQL function. Postgres trusts the IMMUTABLE marker even though
    # technically the dictionary could change — this is the canonical pattern
    # in the Postgres docs and used by Django, Rails, etc.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION reports_tsv(
            p_title TEXT, p_description TEXT, p_tags TEXT[]
        ) RETURNS tsvector
        LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$
            SELECT setweight(to_tsvector('english', coalesce(p_title, '')), 'A') ||
                   setweight(to_tsvector('english', coalesce(p_description, '')), 'B') ||
                   setweight(to_tsvector('english', coalesce(array_to_string(p_tags, ' '), '')), 'C');
        $$;
        """
    )

    op.execute(
        """
        CREATE TABLE reports (
            id              UUID PRIMARY KEY,
            customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
            title           TEXT NOT NULL,
            description     TEXT NOT NULL DEFAULT '',
            tags            TEXT[] NOT NULL DEFAULT '{}',
            generated_at    TIMESTAMPTZ NOT NULL,
            s3_key          TEXT NOT NULL,
            supplementary_files JSONB NOT NULL DEFAULT '[]',
            size_bytes      BIGINT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            search_vector   tsvector GENERATED ALWAYS AS (
                reports_tsv(title, description, tags)
            ) STORED
        );
        """
    )
    op.execute(
        "CREATE INDEX reports_pagination_idx "
        "ON reports (customer_id, generated_at DESC, id DESC);"
    )
    op.execute(
        "CREATE INDEX reports_search_idx ON reports USING GIN (search_vector);"
    )
    op.execute("CREATE INDEX reports_tags_idx ON reports USING GIN (tags);")

    op.execute(
        """
        CREATE TABLE magic_link_tokens (
            token_hash      TEXT PRIMARY KEY,
            customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
            email           TEXT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at      TIMESTAMPTZ NOT NULL,
            consumed_at     TIMESTAMPTZ
        );
        """
    )
    op.execute(
        "CREATE INDEX magic_link_tokens_expires_idx "
        "ON magic_link_tokens (expires_at);"
    )

    op.execute(
        """
        CREATE TABLE idempotency_keys (
            customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
            key             TEXT NOT NULL,
            response_body   JSONB NOT NULL,
            status_code     INT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at      TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (customer_id, key)
        );
        """
    )
    op.execute(
        "CREATE INDEX idempotency_keys_expires_idx "
        "ON idempotency_keys (expires_at);"
    )

    op.execute(
        """
        CREATE TABLE rate_limit_hits (
            scope_key       TEXT NOT NULL,
            window_start    TIMESTAMPTZ NOT NULL,
            count           INT NOT NULL DEFAULT 0,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at      TIMESTAMPTZ NOT NULL,
            PRIMARY KEY (scope_key, window_start)
        );
        """
    )
    op.execute(
        "CREATE INDEX rate_limit_hits_expires_idx "
        "ON rate_limit_hits (expires_at);"
    )

    op.execute(
        """
        CREATE TABLE events (
            id              BIGSERIAL PRIMARY KEY,
            event_type      TEXT NOT NULL,
            customer_id     UUID REFERENCES customers(id) ON DELETE SET NULL,
            occurred_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
            payload         JSONB NOT NULL DEFAULT '{}'
        );
        """
    )
    op.execute(
        "CREATE INDEX events_type_time_idx ON events (event_type, occurred_at DESC);"
    )
    op.execute(
        "CREATE INDEX events_customer_time_idx "
        "ON events (customer_id, occurred_at DESC);"
    )

    op.execute(
        """
        CREATE TABLE sessions (
            id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
            email           TEXT NOT NULL,
            created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
            expires_at      TIMESTAMPTZ NOT NULL,
            last_accessed_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        """
    )
    op.execute("CREATE INDEX sessions_expires_idx ON sessions (expires_at);")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS sessions CASCADE;")
    op.execute("DROP TABLE IF EXISTS events CASCADE;")
    op.execute("DROP TABLE IF EXISTS rate_limit_hits CASCADE;")
    op.execute("DROP TABLE IF EXISTS idempotency_keys CASCADE;")
    op.execute("DROP TABLE IF EXISTS magic_link_tokens CASCADE;")
    op.execute("DROP TABLE IF EXISTS reports CASCADE;")
    op.execute("DROP TABLE IF EXISTS customers CASCADE;")
    op.execute("DROP FUNCTION IF EXISTS reports_tsv(TEXT, TEXT, TEXT[]) CASCADE;")
